
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glbpkpmaqqiueugydhoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsYnBrcG1hcXFpdWV1Z3lkaG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTI5MzgsImV4cCI6MjA2MjE4ODkzOH0.DefRG7GoPCc1VhDW9XszTCtSJywMdztj1IDbBsjht58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define custom type extensions for tables
export interface ConstructItemRow {
  id: number;
  name: string;
  description: string | null;
  duration: number;
  construct_id: number | null;
  phase: string | null;
}

export interface LessonRow {
  id: string;
  school_id?: number | null;
  environment_id?: number | null;
  construct_id?: number | null;
  preparation_time: number;
  main_time: number;
  finish_time: number;
  preparation_role_id?: number | null;
  main_role_id?: number | null;
  finish_role_id?: number | null;
  title: string;
  created_at?: string | null;
  equipment_ids?: number[];
  item_ids?: number[];
  grade: number;
}

export interface RoleType {
  id?: number;
  name?: string;
}
